# Generated by Django 4.2.10 on 2024-02-10 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('car_make', models.IntegerField(default=2024)),
                ('car_mileage', models.IntegerField(default=0)),
                ('car_transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=10)),
                ('car_engine_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=10)),
                ('car_body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van')], default='Sedan', max_length=20)),
                ('car_seating_capacity', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)])),
                ('car_engine_capacity', models.IntegerField(default=1500)),
                ('car_number_of_cylinders', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(16)])),
                ('car_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('black', 'Black'), ('gray', 'Gray')], default='black', max_length=50)),
                ('car_warrenty', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=50)),
                ('car_description', models.TextField(null=True)),
            ],
        ),
    ]
